// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: coco/investment/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgInvestmentGB struct {
	Creator    string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	GameBankId string      `protobuf:"bytes,2,opt,name=gameBankId,proto3" json:"gameBankId,omitempty"`
	Coin       *types.Coin `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin,omitempty"`
}

func (m *MsgInvestmentGB) Reset()         { *m = MsgInvestmentGB{} }
func (m *MsgInvestmentGB) String() string { return proto.CompactTextString(m) }
func (*MsgInvestmentGB) ProtoMessage()    {}
func (*MsgInvestmentGB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d0cc3239c3137c, []int{0}
}
func (m *MsgInvestmentGB) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInvestmentGB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInvestmentGB.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInvestmentGB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInvestmentGB.Merge(m, src)
}
func (m *MsgInvestmentGB) XXX_Size() int {
	return m.Size()
}
func (m *MsgInvestmentGB) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInvestmentGB.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInvestmentGB proto.InternalMessageInfo

func (m *MsgInvestmentGB) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgInvestmentGB) GetGameBankId() string {
	if m != nil {
		return m.GameBankId
	}
	return ""
}

func (m *MsgInvestmentGB) GetCoin() *types.Coin {
	if m != nil {
		return m.Coin
	}
	return nil
}

type MsgInvestmentGBResponse struct {
}

func (m *MsgInvestmentGBResponse) Reset()         { *m = MsgInvestmentGBResponse{} }
func (m *MsgInvestmentGBResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInvestmentGBResponse) ProtoMessage()    {}
func (*MsgInvestmentGBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d0cc3239c3137c, []int{1}
}
func (m *MsgInvestmentGBResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInvestmentGBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInvestmentGBResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInvestmentGBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInvestmentGBResponse.Merge(m, src)
}
func (m *MsgInvestmentGBResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInvestmentGBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInvestmentGBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInvestmentGBResponse proto.InternalMessageInfo

type MsgWithdrawGB struct {
	Creator    string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	GameBankId string      `protobuf:"bytes,2,opt,name=gameBankId,proto3" json:"gameBankId,omitempty"`
	Amount     *types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgWithdrawGB) Reset()         { *m = MsgWithdrawGB{} }
func (m *MsgWithdrawGB) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawGB) ProtoMessage()    {}
func (*MsgWithdrawGB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d0cc3239c3137c, []int{2}
}
func (m *MsgWithdrawGB) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawGB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawGB.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawGB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawGB.Merge(m, src)
}
func (m *MsgWithdrawGB) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawGB) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawGB.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawGB proto.InternalMessageInfo

func (m *MsgWithdrawGB) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgWithdrawGB) GetGameBankId() string {
	if m != nil {
		return m.GameBankId
	}
	return ""
}

func (m *MsgWithdrawGB) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgWithdrawGBResponse struct {
}

func (m *MsgWithdrawGBResponse) Reset()         { *m = MsgWithdrawGBResponse{} }
func (m *MsgWithdrawGBResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawGBResponse) ProtoMessage()    {}
func (*MsgWithdrawGBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6d0cc3239c3137c, []int{3}
}
func (m *MsgWithdrawGBResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawGBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawGBResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawGBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawGBResponse.Merge(m, src)
}
func (m *MsgWithdrawGBResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawGBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawGBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawGBResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgInvestmentGB)(nil), "coco.investment.MsgInvestmentGB")
	proto.RegisterType((*MsgInvestmentGBResponse)(nil), "coco.investment.MsgInvestmentGBResponse")
	proto.RegisterType((*MsgWithdrawGB)(nil), "coco.investment.MsgWithdrawGB")
	proto.RegisterType((*MsgWithdrawGBResponse)(nil), "coco.investment.MsgWithdrawGBResponse")
}

func init() { proto.RegisterFile("coco/investment/tx.proto", fileDescriptor_f6d0cc3239c3137c) }

var fileDescriptor_f6d0cc3239c3137c = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xb1, 0x4e, 0x02, 0x41,
	0x10, 0x86, 0x59, 0x31, 0x18, 0x47, 0x0d, 0xc9, 0x25, 0x86, 0x83, 0x62, 0x43, 0xae, 0x30, 0x34,
	0xec, 0x06, 0x78, 0x03, 0x2c, 0x0c, 0xc5, 0x35, 0xc4, 0xc4, 0x84, 0x6e, 0xef, 0xd8, 0x9c, 0x17,
	0xbc, 0x1d, 0xb2, 0xbb, 0x02, 0x12, 0x1f, 0xc2, 0xb7, 0xf1, 0x15, 0x2c, 0x29, 0x2d, 0x0d, 0xbc,
	0x88, 0x39, 0xe0, 0x04, 0x2e, 0x46, 0x0a, 0xcb, 0xdd, 0x7f, 0xe6, 0xff, 0xfe, 0x99, 0x0c, 0xb8,
	0x21, 0x86, 0xc8, 0x63, 0x35, 0x91, 0xc6, 0x26, 0x52, 0x59, 0x6e, 0x67, 0x6c, 0xac, 0xd1, 0xa2,
	0x53, 0x4e, 0x15, 0xb6, 0x53, 0x6a, 0x34, 0x44, 0x93, 0xa0, 0xe1, 0x81, 0x30, 0x92, 0x4f, 0x5a,
	0x81, 0xb4, 0xa2, 0xc5, 0x43, 0x8c, 0xd5, 0xa6, 0xc1, 0x9b, 0x43, 0xd9, 0x37, 0x51, 0xef, 0xa7,
	0xe1, 0xae, 0xeb, 0xb8, 0x70, 0x16, 0x6a, 0x29, 0x2c, 0x6a, 0x97, 0xd4, 0x49, 0xe3, 0xbc, 0x9f,
	0x3d, 0x1d, 0x0a, 0x10, 0x89, 0x44, 0x76, 0x85, 0x1a, 0xf5, 0x86, 0xee, 0xc9, 0x5a, 0xdc, 0xfb,
	0x71, 0x9a, 0x70, 0x9a, 0x5a, 0xbb, 0xc5, 0x3a, 0x69, 0x5c, 0xb4, 0xab, 0x6c, 0xc3, 0x66, 0x29,
	0x9b, 0x6d, 0xd9, 0xec, 0x16, 0x63, 0xd5, 0x5f, 0x97, 0x79, 0x55, 0xa8, 0xe4, 0xd8, 0x7d, 0x69,
	0xc6, 0xa8, 0x8c, 0xf4, 0x5e, 0xe1, 0xca, 0x37, 0xd1, 0x43, 0x6c, 0x1f, 0x87, 0x5a, 0x4c, 0xff,
	0x15, 0xaa, 0x05, 0x25, 0x91, 0xe0, 0xb3, 0xb2, 0xc7, 0x63, 0x6d, 0x0b, 0xbd, 0x0a, 0x5c, 0x1f,
	0xd0, 0xb3, 0x58, 0xed, 0x77, 0x02, 0x45, 0xdf, 0x44, 0xce, 0x00, 0x2e, 0x0f, 0x56, 0x56, 0x67,
	0xb9, 0xbd, 0xb3, 0xdc, 0x60, 0xb5, 0xc6, 0xb1, 0x8a, 0x8c, 0xe1, 0xdc, 0x03, 0xec, 0xcd, 0x4d,
	0x7f, 0xeb, 0xdb, 0xe9, 0xb5, 0x9b, 0xbf, 0xf5, 0xcc, 0xb5, 0xeb, 0x7f, 0x2c, 0x29, 0x59, 0x2c,
	0x29, 0xf9, 0x5a, 0x52, 0xf2, 0xb6, 0xa2, 0x85, 0xc5, 0x8a, 0x16, 0x3e, 0x57, 0xb4, 0x30, 0xe8,
	0x44, 0xb1, 0x7d, 0x12, 0x01, 0x0b, 0x31, 0xe1, 0xf3, 0x51, 0x24, 0xf4, 0xb0, 0xa3, 0x78, 0x6a,
	0xda, 0x54, 0xd2, 0x4e, 0x51, 0x8f, 0xf8, 0xec, 0xe0, 0xd4, 0x5e, 0xc6, 0xd2, 0x04, 0xa5, 0xf5,
	0xf5, 0x74, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x77, 0x9e, 0xa0, 0xb4, 0x8a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	InvestmentGB(ctx context.Context, in *MsgInvestmentGB, opts ...grpc.CallOption) (*MsgInvestmentGBResponse, error)
	WithdrawGB(ctx context.Context, in *MsgWithdrawGB, opts ...grpc.CallOption) (*MsgWithdrawGBResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) InvestmentGB(ctx context.Context, in *MsgInvestmentGB, opts ...grpc.CallOption) (*MsgInvestmentGBResponse, error) {
	out := new(MsgInvestmentGBResponse)
	err := c.cc.Invoke(ctx, "/coco.investment.Msg/InvestmentGB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawGB(ctx context.Context, in *MsgWithdrawGB, opts ...grpc.CallOption) (*MsgWithdrawGBResponse, error) {
	out := new(MsgWithdrawGBResponse)
	err := c.cc.Invoke(ctx, "/coco.investment.Msg/WithdrawGB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	InvestmentGB(context.Context, *MsgInvestmentGB) (*MsgInvestmentGBResponse, error)
	WithdrawGB(context.Context, *MsgWithdrawGB) (*MsgWithdrawGBResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) InvestmentGB(ctx context.Context, req *MsgInvestmentGB) (*MsgInvestmentGBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvestmentGB not implemented")
}
func (*UnimplementedMsgServer) WithdrawGB(ctx context.Context, req *MsgWithdrawGB) (*MsgWithdrawGBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawGB not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_InvestmentGB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInvestmentGB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InvestmentGB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coco.investment.Msg/InvestmentGB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InvestmentGB(ctx, req.(*MsgInvestmentGB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawGB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawGB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawGB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coco.investment.Msg/WithdrawGB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawGB(ctx, req.(*MsgWithdrawGB))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coco.investment.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvestmentGB",
			Handler:    _Msg_InvestmentGB_Handler,
		},
		{
			MethodName: "WithdrawGB",
			Handler:    _Msg_WithdrawGB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coco/investment/tx.proto",
}

func (m *MsgInvestmentGB) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInvestmentGB) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInvestmentGB) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Coin != nil {
		{
			size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.GameBankId) > 0 {
		i -= len(m.GameBankId)
		copy(dAtA[i:], m.GameBankId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GameBankId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInvestmentGBResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInvestmentGBResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInvestmentGBResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawGB) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawGB) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawGB) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.GameBankId) > 0 {
		i -= len(m.GameBankId)
		copy(dAtA[i:], m.GameBankId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GameBankId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawGBResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawGBResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawGBResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInvestmentGB) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GameBankId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Coin != nil {
		l = m.Coin.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInvestmentGBResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawGB) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GameBankId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawGBResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInvestmentGB) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInvestmentGB: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInvestmentGB: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameBankId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameBankId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Coin == nil {
				m.Coin = &types.Coin{}
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInvestmentGBResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInvestmentGBResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInvestmentGBResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawGB) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawGB: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawGB: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameBankId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameBankId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawGBResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawGBResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawGBResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
